<?php

namespace App\Admin\Controllers;

use App\Models\Theme;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;
use Encore\Admin\Tree;

class ThemeController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'Theme';
    private $id;

    public function index(Content $content)
    {
        $tree = new Tree(new Theme());
        return $content->header('主题设置')->body($tree);
    }

    public function edit($id, Content $content)
    {
        $this->id = $id;
        return parent::edit($id, $content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(Theme::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('parent_id', __('Parent id'));
        $show->field('name', __('Name'));
        $show->field('level', __('Level'));
        $show->field('path', __('Path'));
        $show->field('is_show', __('Is show'));
        $show->field('sort', __('Sort'));

        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new Theme());

        $form->select('parent_id', __('Parent id'))->options(
            array_merge(
                [0 => 'root'],
                Theme::all()->keyBy('id')
                    ->map(function ($item){return $item->name;})
                    ->except([$this->id])->toArray()
            ));
        $form->text('name', __('Name'));
        $form->hidden('level');
        $form->hidden('path');
        $form->switch('is_show', __('Is show'));
        $form->number('sort', __('Sort'))->default(Theme::count()+1);

        $form->saving(function (Form $form){
            if($form->parent_id == 0){
                $form->level = 1;
                $form->path = '-';

            } else {
                $position = Theme::findByParentId($form->parent_id);
                $form->level = ++$position->level;
                $form->path = $position->path.$position->parent_id.'-';
            }
        });
        return $form;
    }
}
